type Project {
  projectName: String!
  peojectDescription: String
  completed: Boolean!
  projectGithubUrl: String
  projectLiveUrl: String
  userId: User
}

type User {
  name: String!
  email: String!
  avatar: String
  password: String!
  hobby: String
  projects: [Project]
}

type Query {
  projects: [Project!]!
}
